# Docker Compose override for development
# This file is automatically loaded by docker-compose for development overrides

version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/sirtifai_dev_db
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_REFRESH_SECRET=dev-refresh-secret-key
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sirtifai_dev_db
